/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.northeastern.cs5500.delivery.controller;

import static com.google.common.truth.Truth.assertThat;
import static com.google.common.truth.Truth.assertWithMessage;
import static org.junit.Assert.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

import edu.northeastern.cs5500.delivery.model.Customer;
import edu.northeastern.cs5500.delivery.model.Delivery;
import edu.northeastern.cs5500.delivery.model.DeliveryDriver;
import edu.northeastern.cs5500.delivery.model.DeliveryStatus;
import edu.northeastern.cs5500.delivery.model.MenuItem;
import edu.northeastern.cs5500.delivery.model.Order;
import edu.northeastern.cs5500.delivery.model.Restaurant;
import edu.northeastern.cs5500.delivery.repository.InMemoryRepository;
import java.time.LocalDateTime;
import java.util.HashMap;
import org.bson.types.ObjectId;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class DeliveryControllerTest {
    public Customer defaultCustomer;
    public DeliveryDriver defaultDeliveryDriver;
    public Order defaultOrder;
    public Restaurant defaultRestaurant;
    public MenuItem item1;
    public ObjectId item1Id;
    public MenuItem item2;
    public ObjectId item2Id;
    public MenuItem item3;
    public ObjectId item3Id;
    HashMap<String, Integer> items = new HashMap<>();
    public DeliveryController deliveryController;
    public Delivery newDelivery;

    @BeforeEach
    public void setup() {
        deliveryController = new DeliveryController(new InMemoryRepository<Delivery>());
        defaultCustomer = new Customer();
        defaultDeliveryDriver = new DeliveryDriver();
        defaultOrder = new Order();
        item1 = new MenuItem();
        item2 = new MenuItem();
        item3 = new MenuItem();
        newDelivery = new Delivery();

        // create a Customer
        defaultCustomer.setUserName("doglover26");
        defaultCustomer.setFirstName("Sanket");
        defaultCustomer.setLastName("Tekans");
        defaultCustomer.setEmail("dogsrock@gmail.com");
        defaultOrder.setCustomer(defaultCustomer);

        // create delivery driver
        defaultDeliveryDriver.setUserName("BobTheDriver");
        defaultDeliveryDriver.setCurrentlyWorking(true);
        newDelivery.setDeliveryDriver(defaultDeliveryDriver);

        // create a valid order with three items
        item1.setName("Kimchi Soup");
        item1.setPrice(999);
        item1.setId(new ObjectId());
        item1Id = item1.getId();
        item2.setName("Bulgogi Beef");
        item2.setPrice(1299);
        item2.setId(new ObjectId());
        item2Id = item2.getId();
        item3.setName("Red Bean Mochi Cake");
        item3.setPrice(325);
        item3.setId(new ObjectId());
        item3Id = item3.getId();
        items.put(item1Id.toString(), 1);
        items.put(item2Id.toString(), 1);
        items.put(item3Id.toString(), 2);
        defaultOrder.setItems(items);

        // create a restuarant with a menu that contains those items
        defaultRestaurant = new Restaurant();
        defaultRestaurant.setRestaurantName("Seoul Cafe");
        HashMap<String, MenuItem> defaultMenu = new HashMap<>();
        defaultMenu.put(item1Id.toString(), item1);
        defaultMenu.put(item2Id.toString(), item2);
        defaultMenu.put(item3Id.toString(), item3);
        defaultRestaurant.setMenuItems(defaultMenu);
        defaultOrder.setRestaurant(defaultRestaurant);

        // complete setup of the new delivery
        defaultDeliveryDriver.setCurrentOrder(defaultOrder);
        newDelivery.setDistance(33.5);
        newDelivery.setOrder(defaultOrder);
    }

    @Test
    void testRegisterCreatesDeliveries() {
        assertThat(deliveryController.getDeliveries()).isNotEmpty();
    }

    @Test
    void testRegisterCreatesValidDeliveries() {
        for (Delivery delivery : deliveryController.getDeliveries()) {
            assertWithMessage(delivery.getNotes()).that(delivery.isValid()).isTrue();
        }
    }

    @Test
    void testCanAddDelivery() throws InvalidDeliveryException, DuplicateKeyException {
        Delivery addedDelivery = deliveryController.addDelivery(newDelivery);
        // check that the delivery has been added to the Delivery repository
        ObjectId addedDeliveryId = addedDelivery.getId();
        newDelivery.setId(addedDeliveryId);
        Delivery addedDeliveryInCollection = deliveryController.getDelivery(addedDeliveryId);
        assertEquals(addedDeliveryInCollection, newDelivery);
    }

    @Test
    void testInvalidOrderOneItemQuantityZero() throws DuplicateKeyException, InvalidOrderException {
        // make a delivery with no items in the order and try to add it
        HashMap<String, Integer> itemsWithZeroQuantity = new HashMap<>();
        itemsWithZeroQuantity.put(item1Id.toString(), 0);
        itemsWithZeroQuantity.put(item2Id.toString(), 0);
        defaultOrder.setItems(itemsWithZeroQuantity);
        newDelivery.setOrder(defaultOrder);
        assertThrows(
                InvalidDeliveryException.class,
                () -> {
                    deliveryController.addDelivery(newDelivery);
                });
    }

    @Test
    void testCreateDelivery() throws DuplicateKeyException, InvalidDeliveryException {
        Delivery createdDelivery = deliveryController.createDelivery(defaultOrder);
        ObjectId createdDeliveryId = createdDelivery.getId();
        assertEquals(defaultOrder, deliveryController.getDelivery(createdDeliveryId).getOrder());
    }

    @Test
    void testCompleteDelivery() throws Exception {
        Delivery addedDelivery = deliveryController.addDelivery(newDelivery);
        Delivery completedDelivery = deliveryController.completeDelivery(addedDelivery);
        assertEquals(DeliveryStatus.DELIVERED, completedDelivery.getDeliveryStatus());
        assertNotNull(completedDelivery.getCompletionTime());
    }

    @Test
    void testCanUpdateDelivery() throws Exception {
        Delivery deliveryToUpdate = deliveryController.addDelivery(newDelivery);
        // check that the order has been added to the Order repository
        ObjectId deliveryId = deliveryToUpdate.getId();
        LocalDateTime deliveryCompletionTime = LocalDateTime.of(2021, 7, 7, 7, 11, 0);
        deliveryToUpdate.setCompletionTime(deliveryCompletionTime);
        deliveryController.updateDelivery(deliveryToUpdate);
        assertEquals(
                deliveryController.getDelivery(deliveryId).getCompletionTime(),
                deliveryCompletionTime);
    }

    @Test
    void testCanDeleteDelivery() throws Exception {
        Delivery addedDelivery = deliveryController.addDelivery(newDelivery);
        ObjectId addedDeliveryId = addedDelivery.getId();
        newDelivery.setId(addedDeliveryId);
        deliveryController.deleteDelivery(addedDeliveryId);
        assertEquals(deliveryController.getDelivery(addedDeliveryId), null);
    }

    @Test
    void testAddInvalidDeliveryExceedsMaxDistance()
            throws InvalidDeliveryException, DuplicateKeyException {
        newDelivery.setDistance(Delivery.MAXIMUM_DISTANCE + 0.001);
        assertThrows(
                InvalidDeliveryException.class,
                () -> {
                    deliveryController.addDelivery(newDelivery);
                });
    }

    @Test
    void testAddInvalidDeliveryNegativeDistance()
            throws InvalidDeliveryException, DuplicateKeyException {
        newDelivery.setDistance(-0.001);
        assertThrows(
                InvalidDeliveryException.class,
                () -> {
                    deliveryController.addDelivery(newDelivery);
                });
    }

    @Test
    void testAddDuplicateDelivery() throws InvalidDeliveryException, DuplicateKeyException {
        Delivery addedDelivery = deliveryController.addDelivery(newDelivery);
        ObjectId addedDeliveryId = addedDelivery.getId();
        newDelivery.setId(addedDeliveryId);
        assertThrows(
                DuplicateKeyException.class,
                () -> {
                    deliveryController.addDelivery(newDelivery);
                });
    }
}
