/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.northeastern.cs5500.delivery.controller;

import org.junit.jupiter.api.Test;

class DeliveryControllerTest {
    @Test
    void testRegisterCreatesDeliveries() {
        //     DeliveryController deliveryController =
        //             new DeliveryController(new InMemoryRepository<Delivery>());
        //     assertThat(deliveryController.getDeliveries()).isNotEmpty();
    }

    @Test
    void testRegisterCreatesValidDeliveries() {
        // DeliveryController deliveryController =
        //         new DeliveryController(new InMemoryRepository<Delivery>());

        // for (Delivery delivery : deliveryController.getDeliveries()) {
        //     assertWithMessage(delivery.getNotes()).that(delivery.isValid()).isTrue();
        // }
    }

    @Test
    void testCanAddDelivery() {
        // This test should NOT call register
        // TODO: implement this test.
    }

    @Test
    void testCanReplaceDelivery() {
        // This test should NOT call register
        // TODO: implement this test.
    }

    @Test
    void testCanDeleteDelivery() {
        // This test should NOT call register
        // TODO: implement this test
    }
}
