/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.northeastern.cs5500.delivery.controller;

import org.junit.jupiter.api.Test;

// import static org.junit.jupiter.api.Assertions.assertTrue;
// package edu.northeastern.cs5500.delivery.controller;

// import static com.google.common.truth.Truth.assertThat;
// // import static com.google.common.truth.Truth.assertWithMessage;

// import edu.northeastern.cs5500.delivery.model.Order;
// import edu.northeastern.cs5500.delivery.repository.InMemoryRepository;

// import static org.junit.jupiter.api.Assertions.assertTrue;
// import org.junit.jupiter.api.Test;

class ReviewControllerTest {
    @Test
    void testRegisterCreatesReviews() {
        // ReviewController reviewController = new ReviewController(new
        // InMemoryRepository<Review>());
        // assertThat(reviewController.getReviews()).isNotEmpty();
    }

    @Test
    void testRegisterCreatesValidReviews() {
        // ReviewController reviewController =
        //           new ReviewController(new InMemoryRepository<Review>());

        //   for (Review review : reviewController.getReviews()) {
        //       assertWithMessage(review.getReviewContent()).that(review.isValid()).isTrue();
        //   }
    }

    @Test
    void testCanAddDelivery() {
        // This test should NOT call register
        // TODO: implement this test.
    }

    @Test
    void testCanReplaceDelivery() {
        // This test should NOT call register
        // TODO: implement this test.
    }

    @Test
    void testCanDeleteDelivery() {
        // This test should NOT call register
        // TODO: implement this test
    }
}
